package Disasm::Capstone::RiscV;

use 5.030000;
use strict;
use warnings;

require Exporter;
use AutoLoader qw(AUTOLOAD);

our @ISA = qw(Exporter Disasm::Capstone);

use constant {
 RISCV_INVALID => 0,
 RISCV_ADD => 1,
 RISCV_ADDI => 2,
 RISCV_ADDIW => 3,
 RISCV_ADDW => 4,
 RISCV_AMOADD_D => 5,
 RISCV_AMOADD_D_AQ => 6,
 RISCV_AMOADD_D_AQ_RL => 7,
 RISCV_AMOADD_D_RL => 8,
 RISCV_AMOADD_W => 9,
 RISCV_AMOADD_W_AQ => 10,
 RISCV_AMOADD_W_AQ_RL => 11,
 RISCV_AMOADD_W_RL => 12,
 RISCV_AMOAND_D => 13,
 RISCV_AMOAND_D_AQ => 14,
 RISCV_AMOAND_D_AQ_RL => 15,
 RISCV_AMOAND_D_RL => 16,
 RISCV_AMOAND_W => 17,
 RISCV_AMOAND_W_AQ => 18,
 RISCV_AMOAND_W_AQ_RL => 19,
 RISCV_AMOAND_W_RL => 20,
 RISCV_AMOMAXU_D => 21,
 RISCV_AMOMAXU_D_AQ => 22,
 RISCV_AMOMAXU_D_AQ_RL => 23,
 RISCV_AMOMAXU_D_RL => 24,
 RISCV_AMOMAXU_W => 25,
 RISCV_AMOMAXU_W_AQ => 26,
 RISCV_AMOMAXU_W_AQ_RL => 27,
 RISCV_AMOMAXU_W_RL => 28,
 RISCV_AMOMAX_D => 29,
 RISCV_AMOMAX_D_AQ => 30,
 RISCV_AMOMAX_D_AQ_RL => 31,
 RISCV_AMOMAX_D_RL => 32,
 RISCV_AMOMAX_W => 33,
 RISCV_AMOMAX_W_AQ => 34,
 RISCV_AMOMAX_W_AQ_RL => 35,
 RISCV_AMOMAX_W_RL => 36,
 RISCV_AMOMINU_D => 37,
 RISCV_AMOMINU_D_AQ => 38,
 RISCV_AMOMINU_D_AQ_RL => 39,
 RISCV_AMOMINU_D_RL => 40,
 RISCV_AMOMINU_W => 41,
 RISCV_AMOMINU_W_AQ => 42,
 RISCV_AMOMINU_W_AQ_RL => 43,
 RISCV_AMOMINU_W_RL => 44,
 RISCV_AMOMIN_D => 45,
 RISCV_AMOMIN_D_AQ => 46,
 RISCV_AMOMIN_D_AQ_RL => 47,
 RISCV_AMOMIN_D_RL => 48,
 RISCV_AMOMIN_W => 49,
 RISCV_AMOMIN_W_AQ => 50,
 RISCV_AMOMIN_W_AQ_RL => 51,
 RISCV_AMOMIN_W_RL => 52,
 RISCV_AMOOR_D => 53,
 RISCV_AMOOR_D_AQ => 54,
 RISCV_AMOOR_D_AQ_RL => 55,
 RISCV_AMOOR_D_RL => 56,
 RISCV_AMOOR_W => 57,
 RISCV_AMOOR_W_AQ => 58,
 RISCV_AMOOR_W_AQ_RL => 59,
 RISCV_AMOOR_W_RL => 60,
 RISCV_AMOSWAP_D => 61,
 RISCV_AMOSWAP_D_AQ => 62,
 RISCV_AMOSWAP_D_AQ_RL => 63,
 RISCV_AMOSWAP_D_RL => 64,
 RISCV_AMOSWAP_W => 65,
 RISCV_AMOSWAP_W_AQ => 66,
 RISCV_AMOSWAP_W_AQ_RL => 67,
 RISCV_AMOSWAP_W_RL => 68,
 RISCV_AMOXOR_D => 69,
 RISCV_AMOXOR_D_AQ => 70,
 RISCV_AMOXOR_D_AQ_RL => 71,
 RISCV_AMOXOR_D_RL => 72,
 RISCV_AMOXOR_W => 73,
 RISCV_AMOXOR_W_AQ => 74,
 RISCV_AMOXOR_W_AQ_RL => 75,
 RISCV_AMOXOR_W_RL => 76,
 RISCV_AND => 77,
 RISCV_ANDI => 78,
 RISCV_AUIPC => 79,
 RISCV_BEQ => 80,
 RISCV_BGE => 81,
 RISCV_BGEU => 82,
 RISCV_BLT => 83,
 RISCV_BLTU => 84,
 RISCV_BNE => 85,
 RISCV_CSRRC => 86,
 RISCV_CSRRCI => 87,
 RISCV_CSRRS => 88,
 RISCV_CSRRSI => 89,
 RISCV_CSRRW => 90,
 RISCV_CSRRWI => 91,
 RISCV_C_ADD => 92,
 RISCV_C_ADDI => 93,
 RISCV_C_ADDI16SP => 94,
 RISCV_C_ADDI4SPN => 95,
 RISCV_C_ADDIW => 96,
 RISCV_C_ADDW => 97,
 RISCV_C_AND => 98,
 RISCV_C_ANDI => 99,
 RISCV_C_BEQZ => 100,
 RISCV_C_BNEZ => 101,
 RISCV_C_EBREAK => 102,
 RISCV_C_FLD => 103,
 RISCV_C_FLDSP => 104,
 RISCV_C_FLW => 105,
 RISCV_C_FLWSP => 106,
 RISCV_C_FSD => 107,
 RISCV_C_FSDSP => 108,
 RISCV_C_FSW => 109,
 RISCV_C_FSWSP => 110,
 RISCV_C_J => 111,
 RISCV_C_JAL => 112,
 RISCV_C_JALR => 113,
 RISCV_C_JR => 114,
 RISCV_C_LD => 115,
 RISCV_C_LDSP => 116,
 RISCV_C_LI => 117,
 RISCV_C_LUI => 118,
 RISCV_C_LW => 119,
 RISCV_C_LWSP => 120,
 RISCV_C_MV => 121,
 RISCV_C_NOP => 122,
 RISCV_C_OR => 123,
 RISCV_C_SD => 124,
 RISCV_C_SDSP => 125,
 RISCV_C_SLLI => 126,
 RISCV_C_SRAI => 127,
 RISCV_C_SRLI => 128,
 RISCV_C_SUB => 129,
 RISCV_C_SUBW => 130,
 RISCV_C_SW => 131,
 RISCV_C_SWSP => 132,
 RISCV_C_UNIMP => 133,
 RISCV_C_XOR => 134,
 RISCV_DIV => 135,
 RISCV_DIVU => 136,
 RISCV_DIVUW => 137,
 RISCV_DIVW => 138,
 RISCV_EBREAK => 139,
 RISCV_ECALL => 140,
 RISCV_FADD_D => 141,
 RISCV_FADD_S => 142,
 RISCV_FCLASS_D => 143,
 RISCV_FCLASS_S => 144,
 RISCV_FCVT_D_L => 145,
 RISCV_FCVT_D_LU => 146,
 RISCV_FCVT_D_S => 147,
 RISCV_FCVT_D_W => 148,
 RISCV_FCVT_D_WU => 149,
 RISCV_FCVT_LU_D => 150,
 RISCV_FCVT_LU_S => 151,
 RISCV_FCVT_L_D => 152,
 RISCV_FCVT_L_S => 153,
 RISCV_FCVT_S_D => 154,
 RISCV_FCVT_S_L => 155,
 RISCV_FCVT_S_LU => 156,
 RISCV_FCVT_S_W => 157,
 RISCV_FCVT_S_WU => 158,
 RISCV_FCVT_WU_D => 159,
 RISCV_FCVT_WU_S => 160,
 RISCV_FCVT_W_D => 161,
 RISCV_FCVT_W_S => 162,
 RISCV_FDIV_D => 163,
 RISCV_FDIV_S => 164,
 RISCV_FENCE => 165,
 RISCV_FENCE_I => 166,
 RISCV_FENCE_TSO => 167,
 RISCV_FEQ_D => 168,
 RISCV_FEQ_S => 169,
 RISCV_FLD => 170,
 RISCV_FLE_D => 171,
 RISCV_FLE_S => 172,
 RISCV_FLT_D => 173,
 RISCV_FLT_S => 174,
 RISCV_FLW => 175,
 RISCV_FMADD_D => 176,
 RISCV_FMADD_S => 177,
 RISCV_FMAX_D => 178,
 RISCV_FMAX_S => 179,
 RISCV_FMIN_D => 180,
 RISCV_FMIN_S => 181,
 RISCV_FMSUB_D => 182,
 RISCV_FMSUB_S => 183,
 RISCV_FMUL_D => 184,
 RISCV_FMUL_S => 185,
 RISCV_FMV_D_X => 186,
 RISCV_FMV_W_X => 187,
 RISCV_FMV_X_D => 188,
 RISCV_FMV_X_W => 189,
 RISCV_FNMADD_D => 190,
 RISCV_FNMADD_S => 191,
 RISCV_FNMSUB_D => 192,
 RISCV_FNMSUB_S => 193,
 RISCV_FSD => 194,
 RISCV_FSGNJN_D => 195,
 RISCV_FSGNJN_S => 196,
 RISCV_FSGNJX_D => 197,
 RISCV_FSGNJX_S => 198,
 RISCV_FSGNJ_D => 199,
 RISCV_FSGNJ_S => 200,
 RISCV_FSQRT_D => 201,
 RISCV_FSQRT_S => 202,
 RISCV_FSUB_D => 203,
 RISCV_FSUB_S => 204,
 RISCV_FSW => 205,
 RISCV_JAL => 206,
 RISCV_JALR => 207,
 RISCV_LB => 208,
 RISCV_LBU => 209,
 RISCV_LD => 210,
 RISCV_LH => 211,
 RISCV_LHU => 212,
 RISCV_LR_D => 213,
 RISCV_LR_D_AQ => 214,
 RISCV_LR_D_AQ_RL => 215,
 RISCV_LR_D_RL => 216,
 RISCV_LR_W => 217,
 RISCV_LR_W_AQ => 218,
 RISCV_LR_W_AQ_RL => 219,
 RISCV_LR_W_RL => 220,
 RISCV_LUI => 221,
 RISCV_LW => 222,
 RISCV_LWU => 223,
 RISCV_MRET => 224,
 RISCV_MUL => 225,
 RISCV_MULH => 226,
 RISCV_MULHSU => 227,
 RISCV_MULHU => 228,
 RISCV_MULW => 229,
 RISCV_OR => 230,
 RISCV_ORI => 231,
 RISCV_REM => 232,
 RISCV_REMU => 233,
 RISCV_REMUW => 234,
 RISCV_REMW => 235,
 RISCV_SB => 236,
 RISCV_SC_D => 237,
 RISCV_SC_D_AQ => 238,
 RISCV_SC_D_AQ_RL => 239,
 RISCV_SC_D_RL => 240,
 RISCV_SC_W => 241,
 RISCV_SC_W_AQ => 242,
 RISCV_SC_W_AQ_RL => 243,
 RISCV_SC_W_RL => 244,
 RISCV_SD => 245,
 RISCV_SFENCE_VMA => 246,
 RISCV_SH => 247,
 RISCV_SLL => 248,
 RISCV_SLLI => 249,
 RISCV_SLLIW => 250,
 RISCV_SLLW => 251,
 RISCV_SLT => 252,
 RISCV_SLTI => 253,
 RISCV_SLTIU => 254,
 RISCV_SLTU => 255,
 RISCV_SRA => 256,
 RISCV_SRAI => 257,
 RISCV_SRAIW => 258,
 RISCV_SRAW => 259,
 RISCV_SRET => 260,
 RISCV_SRL => 261,
 RISCV_SRLI => 262,
 RISCV_SRLIW => 263,
 RISCV_SRLW => 264,
 RISCV_SUB => 265,
 RISCV_SUBW => 266,
 RISCV_SW => 267,
 RISCV_UNIMP => 268,
 RISCV_URET => 269,
 RISCV_WFI => 270,
 RISCV_XOR => 271,
 RISCV_XORI => 272,
};
###
#
# E X P O R T E D   N A M E S
#
###
our @EXPORT = qw(
RISCV_INVALID
RISCV_ADD
RISCV_ADDI
RISCV_ADDIW
RISCV_ADDW
RISCV_AMOADD_D
RISCV_AMOADD_D_AQ
RISCV_AMOADD_D_AQ_RL
RISCV_AMOADD_D_RL
RISCV_AMOADD_W
RISCV_AMOADD_W_AQ
RISCV_AMOADD_W_AQ_RL
RISCV_AMOADD_W_RL
RISCV_AMOAND_D
RISCV_AMOAND_D_AQ
RISCV_AMOAND_D_AQ_RL
RISCV_AMOAND_D_RL
RISCV_AMOAND_W
RISCV_AMOAND_W_AQ
RISCV_AMOAND_W_AQ_RL
RISCV_AMOAND_W_RL
RISCV_AMOMAXU_D
RISCV_AMOMAXU_D_AQ
RISCV_AMOMAXU_D_AQ_RL
RISCV_AMOMAXU_D_RL
RISCV_AMOMAXU_W
RISCV_AMOMAXU_W_AQ
RISCV_AMOMAXU_W_AQ_RL
RISCV_AMOMAXU_W_RL
RISCV_AMOMAX_D
RISCV_AMOMAX_D_AQ
RISCV_AMOMAX_D_AQ_RL
RISCV_AMOMAX_D_RL
RISCV_AMOMAX_W
RISCV_AMOMAX_W_AQ
RISCV_AMOMAX_W_AQ_RL
RISCV_AMOMAX_W_RL
RISCV_AMOMINU_D
RISCV_AMOMINU_D_AQ
RISCV_AMOMINU_D_AQ_RL
RISCV_AMOMINU_D_RL
RISCV_AMOMINU_W
RISCV_AMOMINU_W_AQ
RISCV_AMOMINU_W_AQ_RL
RISCV_AMOMINU_W_RL
RISCV_AMOMIN_D
RISCV_AMOMIN_D_AQ
RISCV_AMOMIN_D_AQ_RL
RISCV_AMOMIN_D_RL
RISCV_AMOMIN_W
RISCV_AMOMIN_W_AQ
RISCV_AMOMIN_W_AQ_RL
RISCV_AMOMIN_W_RL
RISCV_AMOOR_D
RISCV_AMOOR_D_AQ
RISCV_AMOOR_D_AQ_RL
RISCV_AMOOR_D_RL
RISCV_AMOOR_W
RISCV_AMOOR_W_AQ
RISCV_AMOOR_W_AQ_RL
RISCV_AMOOR_W_RL
RISCV_AMOSWAP_D
RISCV_AMOSWAP_D_AQ
RISCV_AMOSWAP_D_AQ_RL
RISCV_AMOSWAP_D_RL
RISCV_AMOSWAP_W
RISCV_AMOSWAP_W_AQ
RISCV_AMOSWAP_W_AQ_RL
RISCV_AMOSWAP_W_RL
RISCV_AMOXOR_D
RISCV_AMOXOR_D_AQ
RISCV_AMOXOR_D_AQ_RL
RISCV_AMOXOR_D_RL
RISCV_AMOXOR_W
RISCV_AMOXOR_W_AQ
RISCV_AMOXOR_W_AQ_RL
RISCV_AMOXOR_W_RL
RISCV_AND
RISCV_ANDI
RISCV_AUIPC
RISCV_BEQ
RISCV_BGE
RISCV_BGEU
RISCV_BLT
RISCV_BLTU
RISCV_BNE
RISCV_CSRRC
RISCV_CSRRCI
RISCV_CSRRS
RISCV_CSRRSI
RISCV_CSRRW
RISCV_CSRRWI
RISCV_C_ADD
RISCV_C_ADDI
RISCV_C_ADDI16SP
RISCV_C_ADDI4SPN
RISCV_C_ADDIW
RISCV_C_ADDW
RISCV_C_AND
RISCV_C_ANDI
RISCV_C_BEQZ
RISCV_C_BNEZ
RISCV_C_EBREAK
RISCV_C_FLD
RISCV_C_FLDSP
RISCV_C_FLW
RISCV_C_FLWSP
RISCV_C_FSD
RISCV_C_FSDSP
RISCV_C_FSW
RISCV_C_FSWSP
RISCV_C_J
RISCV_C_JAL
RISCV_C_JALR
RISCV_C_JR
RISCV_C_LD
RISCV_C_LDSP
RISCV_C_LI
RISCV_C_LUI
RISCV_C_LW
RISCV_C_LWSP
RISCV_C_MV
RISCV_C_NOP
RISCV_C_OR
RISCV_C_SD
RISCV_C_SDSP
RISCV_C_SLLI
RISCV_C_SRAI
RISCV_C_SRLI
RISCV_C_SUB
RISCV_C_SUBW
RISCV_C_SW
RISCV_C_SWSP
RISCV_C_UNIMP
RISCV_C_XOR
RISCV_DIV
RISCV_DIVU
RISCV_DIVUW
RISCV_DIVW
RISCV_EBREAK
RISCV_ECALL
RISCV_FADD_D
RISCV_FADD_S
RISCV_FCLASS_D
RISCV_FCLASS_S
RISCV_FCVT_D_L
RISCV_FCVT_D_LU
RISCV_FCVT_D_S
RISCV_FCVT_D_W
RISCV_FCVT_D_WU
RISCV_FCVT_LU_D
RISCV_FCVT_LU_S
RISCV_FCVT_L_D
RISCV_FCVT_L_S
RISCV_FCVT_S_D
RISCV_FCVT_S_L
RISCV_FCVT_S_LU
RISCV_FCVT_S_W
RISCV_FCVT_S_WU
RISCV_FCVT_WU_D
RISCV_FCVT_WU_S
RISCV_FCVT_W_D
RISCV_FCVT_W_S
RISCV_FDIV_D
RISCV_FDIV_S
RISCV_FENCE
RISCV_FENCE_I
RISCV_FENCE_TSO
RISCV_FEQ_D
RISCV_FEQ_S
RISCV_FLD
RISCV_FLE_D
RISCV_FLE_S
RISCV_FLT_D
RISCV_FLT_S
RISCV_FLW
RISCV_FMADD_D
RISCV_FMADD_S
RISCV_FMAX_D
RISCV_FMAX_S
RISCV_FMIN_D
RISCV_FMIN_S
RISCV_FMSUB_D
RISCV_FMSUB_S
RISCV_FMUL_D
RISCV_FMUL_S
RISCV_FMV_D_X
RISCV_FMV_W_X
RISCV_FMV_X_D
RISCV_FMV_X_W
RISCV_FNMADD_D
RISCV_FNMADD_S
RISCV_FNMSUB_D
RISCV_FNMSUB_S
RISCV_FSD
RISCV_FSGNJN_D
RISCV_FSGNJN_S
RISCV_FSGNJX_D
RISCV_FSGNJX_S
RISCV_FSGNJ_D
RISCV_FSGNJ_S
RISCV_FSQRT_D
RISCV_FSQRT_S
RISCV_FSUB_D
RISCV_FSUB_S
RISCV_FSW
RISCV_JAL
RISCV_JALR
RISCV_LB
RISCV_LBU
RISCV_LD
RISCV_LH
RISCV_LHU
RISCV_LR_D
RISCV_LR_D_AQ
RISCV_LR_D_AQ_RL
RISCV_LR_D_RL
RISCV_LR_W
RISCV_LR_W_AQ
RISCV_LR_W_AQ_RL
RISCV_LR_W_RL
RISCV_LUI
RISCV_LW
RISCV_LWU
RISCV_MRET
RISCV_MUL
RISCV_MULH
RISCV_MULHSU
RISCV_MULHU
RISCV_MULW
RISCV_OR
RISCV_ORI
RISCV_REM
RISCV_REMU
RISCV_REMUW
RISCV_REMW
RISCV_SB
RISCV_SC_D
RISCV_SC_D_AQ
RISCV_SC_D_AQ_RL
RISCV_SC_D_RL
RISCV_SC_W
RISCV_SC_W_AQ
RISCV_SC_W_AQ_RL
RISCV_SC_W_RL
RISCV_SD
RISCV_SFENCE_VMA
RISCV_SH
RISCV_SLL
RISCV_SLLI
RISCV_SLLIW
RISCV_SLLW
RISCV_SLT
RISCV_SLTI
RISCV_SLTIU
RISCV_SLTU
RISCV_SRA
RISCV_SRAI
RISCV_SRAIW
RISCV_SRAW
RISCV_SRET
RISCV_SRL
RISCV_SRLI
RISCV_SRLIW
RISCV_SRLW
RISCV_SUB
RISCV_SUBW
RISCV_SW
RISCV_UNIMP
RISCV_URET
RISCV_WFI
RISCV_XOR
RISCV_XORI
);

1;

__END__